### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by ascariandrea** [FrancescoCioria/smooth-release#77]
I tried many times to smooth-release a npm package without any success.
This is the error I get when I *smooth-release* `scriptoni`.

```
$npm run release-version

> scriptoni@0.2.2 release-version /Users/andreaascari/Workspace/buildo/scriptoni
> smooth-release


RUN VALIDATIONS
---------------

✓ Validate branch

✓ Validate uncommitted changes

✓ Validate untracked files

✓ Validate sync with remote

✓ Validate user's credentials for "npm"

? Do you want to run the "npm-version" task and increase the version of your library? (y/n) y



INCREASE VERSION IN "PACKAGE.JSON"
----------------------------------

Compute release
✖ Get all tags from GitHub


 Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at /Users/andreaascari/Workspace/buildo/scriptoni/node_modules/octokat/dist/node/request.js:231:19
    at xhr.onreadystatechange (/Users/andreaascari/Workspace/buildo/scriptoni/node_modules/octokat/dist/node/request.js:45:18)
    at dispatchEvent (/Users/andreaascari/Workspace/buildo/scriptoni/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/andreaascari/Workspace/buildo/scriptoni/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/andreaascari/Workspace/buildo/scriptoni/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/andreaascari/.nvm/versions/node/v6.9.2/bin/node" "/Users/andreaascari/.nvm/versions/node/v6.9.2/bin/npm" "run" "release-version"
npm ERR! node v6.9.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! scriptoni@0.2.2 release-version: `smooth-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scriptoni@0.2.2 release-version script 'smooth-release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scriptoni package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     smooth-release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scriptoni
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scriptoni
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andreaascari/Workspace/buildo/scriptoni/npm-debug.log
```

**Comment by FrancescoCioria** [comment]
@ascariandrea this is probably caused by an invalid GitHub token. Replace it with  new token and it should work again.
I already tried to add a validation step for GitHub credentials but unfortunately I couldn't find a way to do it
